### ISSUE TITLE
makedirs() unexpected keyword argument

### ISSUE THREAD

**Issue by hexstr1p** [appleorange1/openmailbox_downloader#4]
First, trying to run it with `./uidextract.py` results in `/usr/bin/python3: bad interpreter: No such file or directory`. So it has to be run with `python uidextract.py`.

Second, after retrieving the list of emails this error occurs:
```
line 30, in get_emails
    os.makedirs('emails_output_dir', exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```

**Comment by hexstr1p** [comment]
The solution is to modify line 30 in that file so that it reads
```
os.makedirs('emails_output_dir')
```

**Comment by batterystaples** [comment]
The issue is that you don't have Python 3 installed, and you're trying to run the script with Python 2. Python 2 [will not be maintained past 2020](https://pythonclock.org/), so if you're still using Python 2, you should probably switch now.
